[package]
name = "prob293"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primal = "0.3.2"
rayon = "1.10.0"
time = "0.3.34"
